config/routes.rb
Rails.application.routes.draw do
  root to: 'divisions#index'
  resources :divisions do
    resources :employees
  end
  resources :employees
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :employees
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :division
  has_many :employee_projects
  has_many :projects, :through => :employee_projects
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
  belongs_to :project
  belongs_to :employee
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :employee_projects
  has_many :employees, :through => :employee_projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  def index
    @divisions = Division.all
    render :index
  end

  def new
    @division = Division.new
    render :new
  end

  def create
    @division = Division.new(division_params)
    if @division.save
      redirect_to divisions_path
    else
      render :new
    end
  end

  def edit
    @division = Division.find(params[:id])
    render :edit
  end

  def show
    @division = Division.find(params[:id])
    render :show
  end

  def update
    @division = Division.find(params[:id])
    if @division.update(division_params)
      redirect_to divisions_path
    else
      render :edit
    end
  end

  def destroy
    @division = Division.find(params[:id])
    @division.destroy
    redirect_to divisions_path
  end

  private
    def division_params
      params.require(:division).permit(:name)
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new
    render :new
  end

  def create
    @division = Division.find(params[:division_id])
    @employee = @division.employees.new(employee_params)
    if @employee.save
      redirect_to division_path(@division)
    else
      render :new
    end
  end

  def show
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:id])
    render :show
  end

  def edit
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:id])
    render :edit
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to division_path(@employee.division)
    else
      render :edit
    end
  end

  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to division_path(@employee.division)
  end

  private
    def employee_params
      params.require(:employee).permit(:first_name, :last_name)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
    render :index
  end

  def new
    @project = Project.new
    render :new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path()
    else
      render :new
    end
  end

  def show
    @division = Division.find(params[:division_id])
    @employee = Employee.find(params[:employee_id])
    @project = Project.find(params[:id])
    render :show
  end

  def edit
    @employee = Employee.find(params[:employee_id])
    @project = Project.find(params[:id])
    render :edit
  end

  private
    def project_params
      params.require(:project).permit(:name)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/divisions/edit.html.erb
<h1>Edit division</h1>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/divisions/index.html.erb
<h1>Divisions</h1>

<% if @divisions.any? %>
  <ul>
    <% @divisions.each do |division| %>
      <li><%= link_to division.name, division_path(division) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no divisions yet.</p>
<% end %>


<p><%= link_to "Create new division", new_division_path %></p>

<p><%= link_to "Projects", projects_path %></p>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= form_for @division do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit  %>
<% end %>

app/views/divisions/show.html.erb
<h1><%= @division.name %></h1>

<% if @division.employees.any? %>
  <h4>Here are the employees associated with this division:</h4>

  <% @division.employees.each do |employee| %>
    <ul>
      <li><%= link_to (employee.first_name + " " + employee.last_name), division_employee_path(@division, employee) %></li>
    </ul>
  <% end %>
<% else %>
  <p>No employees are assigned to this division.</p>
<% end %>

<p><%= link_to "Add an employee", new_division_employee_path(@division) %></p>
<p><%= link_to "Edit", edit_division_path(@division) %></p>
<p><%= link_to "Delete", division_path(@division),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to divisions", divisions_path %></p>

app/views/employees/edit.html.erb
<h1>Edit Employee:</h1>

<%= form_for [@division, @employee] do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <p><%= f.submit %></p>
<% end %>

app/views/employees/new.html.erb
<h1>Add a new employee:</h1>

<%= form_for [@division, @employee] do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <p><%= f.submit %></p>
<% end %>

app/views/employees/show.html.erb
<h1>Employee: <%= (@employee.first_name + @employee.last_name) %></h1>
<h2>Division: <%= @division.name %></h2>

<p><%= link_to "Edit", edit_division_employee_path(@division, @employee) %></p>
<p><%= link_to "Delete", division_employee_path(@division, @employee),
                         :data => {:confirm => "Are you sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to division", division_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<h1>Edit Project:</h1>

<%= form_for [@employee, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<% if @projects.any? %>
  <ul>
    <% @projects.each do |project| %>
      <li><%= link_to project.name, project_path(project) %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no projects yet.</p>
<% end %>


<p><%= link_to "Create new project", new_project_path %></p>

<p><%= link_to "Projects", projects_path %></p>

app/views/projects/new.html.erb
<h1>Add a new project:</h1>

<%= form_for [@project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <p><%= f.submit %></p>
<% end %>

app/views/projects/show.html.erb
<h1>Employee: <%= (@employee.first_name + @employee.last_name) %></h1>
<h2>Project: <%= @project.name %></h2>

<p><%= link_to "Edit", edit_employee_project_path(@employee, @project) %></p>
<p><%= link_to "Delete", employee_project_path(@employee, @project),
                         :data => {:confirm => "Are you sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to division", employee_path %></p>